!if %not(%variable_exists("$BGCOLOR"))
' FFFFFF had issues at times
!$BGCOLOR = "#FFFFFE"
!endif

skinparam backgroundColor $BGCOLOR
skinparam useBetaStyle false

' skinparam roundcorner 20

skinparam title {
	FontColor	                 #000
	BorderColor	                 #c2c2c2
	' FontSize	    	         16
	BorderRoundCorner            8
	BorderThickness 	         1
	BackgroundColor              #f5f5f5-#f2f2f2
}

skinparam rectangle {
	BorderThickness 2
	BorderColor #gray
}

!definelong Client(e_alias, e_label)
rectangle "e_label" as e_alias #lawngreen
!enddefinelong

!definelong Manager(e_alias, e_label)
rectangle "e_label" as e_alias #yellow
!enddefinelong

!definelong Engine(e_alias, e_label)
rectangle "e_label" as e_alias #orange
!enddefinelong

!definelong Accessor(e_alias, e_label)
rectangle "e_label" as e_alias #lightgray
!enddefinelong

!definelong Util(e_alias, e_label)
rectangle "e_label" as e_alias #violet
!enddefinelong

!definelong Resource(e_alias, e_label)
rectangle "e_label" as e_alias #aqua
!enddefinelong

!definelong Db(e_alias, e_label)
database "e_label" as e_alias #aqua
!enddefinelong

!definelong Gateway(e_alias, e_label)
rectangle "e_label" as e_alias #goldenrod
'#DAA520 / goldenrod
!enddefinelong

!definelong Agent(e_alias, e_label)
rectangle "e_label" as e_alias #moccasin
'#FFE4B5 / moccasin
!enddefinelong
